package org.snake.client.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
import org.snake.client.sound.MP3;
import org.snake.util.ObjectAction;

/**
 *
 * @author Faris
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings = new javax.swing.JLabel();
        easySetting = new javax.swing.JCheckBox();
        mediumSetting = new javax.swing.JCheckBox();
        hardSetting = new javax.swing.JCheckBox();
        legendSetting = new javax.swing.JCheckBox();
        DIFFICULTY_FIELD = new javax.swing.JLabel();
        errorSettingsLabel = new javax.swing.JLabel();
        setSettings = new javax.swing.JButton();
        musicToggle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        settings.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        settings.setText("Settings");

        easySetting.setText("Easy");
        easySetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easySettingActionPerformed(evt);
            }
        });

        mediumSetting.setText("Medium");
        mediumSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumSettingActionPerformed(evt);
            }
        });

        hardSetting.setText("Hard");

        legendSetting.setText("Legend");
        legendSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legendSettingActionPerformed(evt);
            }
        });

        DIFFICULTY_FIELD.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        DIFFICULTY_FIELD.setText("Difficulty");

        errorSettingsLabel.setText("Please select ONE difficulty setting");

        setSettings.setText("Finished");

        musicToggle.setText("Music & Sound");
        musicToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicToggleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel1.setText("Audio");

        returnButton.setText("Cancel");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnButton)
                        .addGap(53, 53, 53)
                        .addComponent(setSettings))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(settings)
                        .addGap(12, 12, 12))
                    .addComponent(errorSettingsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(legendSetting)
                                    .addComponent(hardSetting)
                                    .addComponent(mediumSetting)
                                    .addComponent(easySetting)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel1))))
                            .addComponent(DIFFICULTY_FIELD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(musicToggle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settings)
                .addGap(1, 1, 1)
                .addComponent(errorSettingsLabel)
                .addGap(28, 28, 28)
                .addComponent(DIFFICULTY_FIELD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(easySetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediumSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legendSetting)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setSettings)
                    .addComponent(returnButton))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void easySettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easySettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easySettingActionPerformed

    private void mediumSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumSettingActionPerformed

    private void legendSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legendSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legendSettingActionPerformed

    private void musicToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicToggleActionPerformed
        if(MP3.musicPlaying)
            try {
            ObjectAction.getMp3().close();
        } catch (JavaLayerException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
            ObjectAction.getMp3().play();
    }//GEN-LAST:event_musicToggleActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        ObjectAction.getClient().changeToFrame(new MainMenu());
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DIFFICULTY_FIELD;
    private javax.swing.JCheckBox easySetting;
    private javax.swing.JLabel errorSettingsLabel;
    private javax.swing.JCheckBox hardSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox legendSetting;
    private javax.swing.JCheckBox mediumSetting;
    private javax.swing.JToggleButton musicToggle;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton setSettings;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables
}
